name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install xmllint
      run: sudo apt install libxft-dev libx11-dev xserver-xorg-dev xorg-dev
    - name: release
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose

